import{a as m,S as g,i as u}from"./assets/vendor-D9tHNiur.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();m.defaults.baseURL="https://pixabay.com/api/";const h="49133693-4042ac5cb8c0a8ba13ba0f36c";let l=1,d="";async function b(o){try{o!==d&&(l=1,d=o);const t=await m.get("/",{params:{key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:15}});return l++,t.data.hits}catch(t){return console.error("Помилка:",t),[]}}const y=document.querySelector(".gallery");let L=new g(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1});function v(){y.innerHTML=""}function w(o){const t=o.map(s=>{const{webformatURL:a,largeImageURL:e,tags:r,likes:n,views:q,comments:M,downloads:O}=s;return`<li class="gallery-item">
      <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${r}" class="gallery-image" width="640" height="360" />
            </a>
            <div class="gallery-info">
	          <p class="gallery-info-name">likes<span class="galery-info-value">${s.likes}</span></p>
	          <p class="gallery-info-name">views<span class="galery-info-value">${s.views}</span></p>
	          <p class="gallery-info-name">comments<span class="galery-info-value">${s.comments}</span></p>
            <p class="gallery-info-name">downloads<span class="galery-info-value">${s.downloads}</span></p>
            </div>
        </li>`}).join("");y.insertAdjacentHTML("beforeend",t),L.refresh()}const p=document.querySelector(".form"),S=document.querySelector(".input-form"),f=document.querySelector(".loader"),$=document.querySelector(".gallery"),c=document.querySelector(".btn-load-more");let i="";p.addEventListener("submit",async o=>{if(o.preventDefault(),c.classList.add("is-hidden"),i=S.value.trim(),i===""){u.show({message:"Поле не може бути порожнім. Введіть текст для пошуку...",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}f.style.display="block",v();try{b(i).then(t=>{if(t.length===0){$.innerHTML="",u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}w(t),c.classList.remove("is-hidden")})}catch(t){console.log(t)}finally{f.style.display="none"}p.reset()});c.addEventListener("click",onLoadMore);
//# sourceMappingURL=index.js.map
