import{a as y,i as u,S as b}from"./assets/vendor-D9tHNiur.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();y.defaults.baseURL="https://pixabay.com/api/";const L="49133693-4042ac5cb8c0a8ba13ba0f36c",v=document.querySelector(".btn-load-more");let i=1,p="",w=15;const S=Math.ceil(500/w);async function m(t){if(i>S)return v.classList.add("is-hidden"),u.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});try{t!==p&&(i=1,p=t);const r=await y.get("/",{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:15}});return i++,r.data.hits}catch(r){return console.error("Помилка:",r),[]}}const g=document.querySelector(".gallery");let $=new b(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1});function q(){g.innerHTML=""}function h(t){const r=t.map(o=>{const{webformatURL:n,largeImageURL:e,tags:s,likes:l,views:O,comments:R,downloads:x}=o;return`<li class="gallery-item">
      <a href="${e}" class="gallery-link">
            <img src="${n}" alt="${s}" class="gallery-image" width="640" height="360" />
            </a>
            <div class="gallery-info">
	          <p class="gallery-info-name">likes<span class="galery-info-value">${o.likes}</span></p>
	          <p class="gallery-info-name">views<span class="galery-info-value">${o.views}</span></p>
	          <p class="gallery-info-name">comments<span class="galery-info-value">${o.comments}</span></p>
            <p class="gallery-info-name">downloads<span class="galery-info-value">${o.downloads}</span></p>
            </div>
        </li>`}).join("");g.insertAdjacentHTML("beforeend",r),$.refresh()}const f=document.querySelector(".form"),M=document.querySelector(".input-form"),d=document.querySelector(".loader"),P=document.querySelector(".gallery"),a=document.querySelector(".btn-load-more");let c="";f.addEventListener("submit",async t=>{if(t.preventDefault(),a.classList.add("is-hidden"),c=M.value.trim(),c===""){u.show({message:"Поле не може бути порожнім. Введіть текст для пошуку...",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}d.style.display="block",q();try{m(c).then(r=>{if(r.length===0){P.innerHTML="",u.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}h(r),a.classList.remove("is-hidden")})}catch(r){console.log(r)}finally{d.style.display="none"}f.reset()});a.addEventListener("click",k);async function k(){d.style.display="block";try{const t=await m(c);if(t.length===0){a.classList.remove("is-hidden");return}if(h(t),t.length<15){a.classList.add("is-hidden");return}}catch(t){console.log(t)}finally{d.style.display="none"}}
//# sourceMappingURL=index.js.map
