import{a as u,S as p,i as l}from"./assets/vendor-D9tHNiur.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";const d="49133693-4042ac5cb8c0a8ba13ba0f36c";function m(s){return u.get("/",{params:{key:d,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data.hits).catch(r=>(console.error("Помилка:",r),[]))}const f=document.querySelector(".gallery");let y=new p(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1});function g(){f.innerHTML=""}function h(s){g();const r=s.map(o=>{const{webformatURL:a,largeImageURL:e,tags:t,likes:n,views:w,comments:L,downloads:S}=o;return`<li class="gallery-item">
      <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${t}" class="gallery-image" width="640" height="360" />
            </a>
            <div class="gallery-info">
	          <p class="gallery-info-name">likes<span class="galery-info-value">${o.likes}</span></p>
	          <p class="gallery-info-name">views<span class="galery-info-value">${o.views}</span></p>
	          <p class="gallery-info-name">comments<span class="galery-info-value">${o.comments}</span></p>
            <p class="gallery-info-name">downloads<span class="galery-info-value">${o.downloads}</span></p>
            </div>
        </li>`}).join("");f.insertAdjacentHTML("beforeend",r),y.refresh()}const i=document.querySelector(".form"),b=document.querySelector(".input-form"),c=document.querySelector(".loader"),v=document.querySelector(".gallery");i.addEventListener("submit",s=>{s.preventDefault();const r=b.value.trim();if(r===""){l.show({message:"Поле не може бути порожнім. Введіть текст для пошуку...",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}c.style.display="block",m(r).then(o=>{if(o.length===0){v.innerHTML="",l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"#ef4040",position:"topRight",class:"custom-toast"});return}h(o)}).catch(o=>console.log(o)).finally(()=>{c.style.display="none"}),i.reset()});
//# sourceMappingURL=index.js.map
